http:
  middlewares:
    for-dev:
      chain:
        middlewares:
          - compress-it
          - cors-headers
          - security-headers
          - cache-headers
    authtraefik:
      basicAuth:
        users:
          - 'admin:$2y$10$22uFpzSDEHO/zNsC1U0tte.YPNLAN2AMxpvXkJwQmFgPXow0xP1py'
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    compress-it:
      compress: {}
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        browserXssFilter: true
        stsSeconds: 15552000
        forceSTSHeader: true
    cors-headers:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - Origin
          - Authorization
          - Content-Type
        accessControlAllowMethods:
          - OPTION
          - GET
          - POST
          - PUT
          - PATCH
        accessControlAllowOriginList:
          - '*'
        accessControlMaxAge: 100
        addVaryHeader: true
    cache-headers:
      headers:
        customResponseHeaders:
          Cache-Control: 'no-cache, max-age=0'
