global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'docker'
    static_configs:
      - targets: ['docker-socket-proxy:2375']

  # Découverte automatique des services Docker
  - job_name: 'docker-services'
    docker_sd_configs:
      - host: tcp://docker-socket-proxy:2375
        port: 9090
