version: '3.8'

networks:
  traefik:
    external:
      name: traefik

services:

  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: always
    read_only: true
    ports:
      - ${HOST_UNSECURE_PORT-80}:80
      - ${HOST_SECURE_PORT-443}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/dynamic_conf.d:/etc/traefik/dynamic_conf.d
      - ${CERTS_DIR-../certs}:/etc/certs
    labels:
      traefik.enable: true
      # Dashboard
      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: authtraefik@file
      # Global redirect to https
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: "redirect-to-https@file"
    networks:
      - traefik
