api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

providers:
  docker:
    watch: true
    endpoint: 'tcp://docker-socket-proxy:2375'
    exposedByDefault: false
    network: traefik
  file:
    watch: true
    directory: /etc/traefik/dynamic_conf.d
