api:
  dashboard: true
#  insecure: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    watch: true
    exposedByDefault: false
    network: "traefik"
  file:
    watch: true
    directory: "/etc/traefik/dynamic_conf.d"
