version: '3.8'

networks:
  traefik:
    external:
      name: traefik
  docker-socket-proxy:
    external:
      name: docker-socket-proxy

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    command: -H tcp://docker-socket-proxy:2375
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - portainer_data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`portainer.localhost`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - traefik
      - docker-socket-proxy

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.rule: Host(`adminer.localhost`)
      traefik.http.routers.adminer.entrypoints: websecure
      traefik.http.routers.adminer.tls: true
    networks:
      - traefik

  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.maildev.rule: Host(`maildev.localhost`)
      traefik.http.routers.maildev.entrypoints: websecure
      traefik.http.routers.maildev.tls: true
      traefik.http.services.maildev.loadbalancer.server.port: 80
    networks:
      - traefik

volumes:
  portainer_data:
