version: '3.9'

networks:
  traefik:
    external:
      name: traefik
  docker-socket-proxy:
    external:
      name: docker-socket-proxy

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    command: -H tcp://docker-socket-proxy:2375 --http-enabled
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - portainer_data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`portainer.localhost`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - traefik
      - docker-socket-proxy

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.adminer.rule: Host(`adminer.localhost`)
      traefik.http.routers.adminer.entrypoints: websecure
      traefik.http.routers.adminer.tls: true
      traefik.http.routers.adminer.middlewares: authtraefik@file
    networks:
      - traefik

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    external_links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - /sessions
    labels:
      traefik.enable: true
      traefik.http.routers.pma.rule: Host(`phpmyadmin.localhost`)
      traefik.http.routers.pma.entrypoints: websecure
      traefik.http.routers.pma.tls: true
      traefik.http.routers.pma.middlewares: authtraefik@file
    networks:
      - traefik

  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    restart: always
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    labels:
      traefik.enable: true
      traefik.http.routers.maildev.rule: Host(`maildev.localhost`)
      traefik.http.routers.maildev.entrypoints: websecure
      traefik.http.routers.maildev.tls: true
      traefik.http.services.maildev.loadbalancer.server.port: 80
    networks:
      - traefik

volumes:
  portainer_data:
