version: '3.8'

networks:
  traefik:
    external:
      name: 'traefik'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - portainer_data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: web
      traefik.http.routers.portainer.rule: Host(`portainer.localhost`)
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - traefik

  maildev:
    container_name: 'maildev'
    image: djfarrelly/maildev
    restart: 'always'
    labels:
      traefik.enable: true
      traefik.http.routers.mail.rule: Host(`maildev.localhost`)
      traefik.http.routers.mail.entrypoints: web
      traefik.http.services.mail.loadbalancer.server.port: 80
    networks:
      - traefik

volumes:
  portainer_data:
